Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false
