version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - nginx:/cache/
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis:/data/
    restart: always

volumes:
  nginx:
  redis:
