name: Continuous Integration

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  schedule:
    - cron: '0 7 * * 1'

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ "2.6", "2.7", "3.0" ]

    container:
      image: ruby:3.0-alpine

    services:
      redis:
        image: redis:alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add build-base git cmake openssl-dev
          apk add tar

      - name: Cache Gems
        uses: actions/cache@v2.1.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gem-

      - name: Install Gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Test
        env:
          MA_ENDPOINT: ${{ secrets.MA_ENDPOINT }}
          MA_ENDPOINT_USER: ${{ secrets.MA_ENDPOINT_USER }}
          MA_ENDPOINT_PASSWORD: ${{ secrets.MA_ENDPOINT_PASSWORD }}
          WEBMOCK_ALLOW_HOST: ${{ secrets.WEBMOCK_ALLOW_HOST }}
          REDIS_URL: "redis://redis:6379/"
        run: bundle exec rspec --profile 10 --format progress

      - name: Lint
        run: bundle exec rubocop --parallel --display-cop-names

  release:
    name: Release application
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Build and push to RubyGems
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Gem ${{ github.event.repository.name }} ${{ env.VERSION }} was released
