name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    name: Continuous Integration
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ "2.5", "2.6", "2.7", "3.0" ]

    container:
      image: ruby:3.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add tar

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        env:
          MA_ENDPOINT: ${{ secrets.MA_ENDPOINT }}
          MA_ENDPOINT_USER: ${{ secrets.MA_ENDPOINT_USER }}
          MA_ENDPOINT_PASSWORD: ${{ secrets.MA_ENDPOINT_PASSWORD }}
          WEBMOCK_ALLOW_HOST: ${{ secrets.WEBMOCK_ALLOW_HOST }}
        run: bundle exec rspec --profile 10 --format progress

      - name: Lint
        run: bundle exec rubocop --parallel --display-cop-names
